export const INSTAGRAM_CLIENT_ID = process.env.INSTAGRAM_CLIENT_ID
export const INSTAGRAM_CLIENT_SECRET = process.env.INSTAGRAM_CLIENT_SECRET
export const INSTAGRAM_REDIRECT_URI = process.env.INSTAGRAM_REDIRECT_URI
