export const ROUTE_ITEMS = {
    home: '/',
    foodAndDrink: '/food-and-drink',
    cities: '/cities',
    search: '/search',
    city: '/city',
    restaurant: '/restaurant',
    userProfile: '/user-profile',
    recommendationList: '/recommendation-list',
    admin: '/admin',
    adminCities: 'cities',
    adminFlaggedContent: 'flagged-content',
    adminRecommendationLists: 'recommendation-lists',
    termsAndConditions: '/terms-of-use',
    me: '/user-profile/me',
    influencerWelcome: '/influencer-welcome',
    myLists: '/user-profile/me/#myLists',
}
