import { sourceEnum } from './enumerations'

export interface ICategory {
    id?: number
    longName: string
    source?: sourceEnum
    sourceId?: number
    tagName: string
}

export const mockCategoryList: ICategory[] = [
    { tagName: 'Ainu', longName: 'Ainu', id: 0, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Albanian', longName: 'Albanian', id: 1, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Argentine', longName: 'Argentine', id: 2, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Andhra', longName: 'Andhra', id: 3, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Anglo-Indian', longName: 'Anglo-Indian', id: 4, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Arab', longName: 'Arab', id: 5, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Armenian', longName: 'Armenian', id: 6, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Assyrian', longName: 'Assyrian', id: 7, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Awadhi', longName: 'Awadhi', id: 8, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Azerbaijani', longName: 'Azerbaijani', id: 9, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Balochi', longName: 'Balochi', id: 10, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Belarusian', longName: 'Belarusian', id: 11, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Bangladeshi', longName: 'Bangladeshi', id: 12, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Bengali', longName: 'Bengali', id: 13, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Berber', longName: 'Berber', id: 14, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Brazilian', longName: 'Brazilian', id: 15, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Buddhist', longName: 'Buddhist', id: 16, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Bulgarian', longName: 'Bulgarian', id: 17, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Cajun', longName: 'Cajun', id: 18, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Cantonese', longName: 'Cantonese', id: 19, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Caribbean', longName: 'Caribbean', id: 20, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Chechen', longName: 'Chechen', id: 21, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Chinese cuisine', longName: 'Chinese cuisine', id: 22, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Chinese Islamic', longName: 'Chinese Islamic', id: 23, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Circassian', longName: 'Circassian', id: 24, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Crimean Tatar', longName: 'Crimean Tatar', id: 25, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Cypriot', longName: 'Cypriot', id: 26, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Danish', longName: 'Danish', id: 27, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'English', longName: 'English', id: 28, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Estonian', longName: 'Estonian', id: 29, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'French', longName: 'French', id: 30, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Filipino', longName: 'Filipino', id: 31, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Georgian', longName: 'Georgian', id: 32, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'German', longName: 'German', id: 33, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Goan', longName: 'Goan', id: 34, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Goan Catholic', longName: 'Goan Catholic', id: 35, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Greek', longName: 'Greek', id: 36, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Gujarati', longName: 'Gujarati', id: 37, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Hyderabad', longName: 'Hyderabad', id: 38, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Indian cuisine', longName: 'Indian cuisine', id: 39, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Indian Chinese', longName: 'Indian Chinese', id: 40, source: sourceEnum.Yelp, sourceId: null },
    {
        tagName: 'Indian Singaporean cuisine',
        longName: 'Indian Singaporean cuisine',
        id: 41,
        source: sourceEnum.Yelp,
        sourceId: null,
    },
    { tagName: 'Indonesian', longName: 'Indonesian', id: 42, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Inuit', longName: 'Inuit', id: 43, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Irish', longName: 'Irish', id: 44, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Italian-American', longName: 'Italian-American', id: 45, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Italian cuisine', longName: 'Italian cuisine', id: 46, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Jamaican', longName: 'Jamaican', id: 47, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Japanese', longName: 'Japanese', id: 48, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Jewish', longName: 'Jewish', id: 49, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Karnataka', longName: 'Karnataka', id: 50, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Kazakh', longName: 'Kazakh', id: 51, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Keralite', longName: 'Keralite', id: 52, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Korean', longName: 'Korean', id: 53, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Kurdish', longName: 'Kurdish', id: 54, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Laotian', longName: 'Laotian', id: 55, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Lebanese', longName: 'Lebanese', id: 56, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Latvian', longName: 'Latvian', id: 57, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Lithuanian', longName: 'Lithuanian', id: 58, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Louisiana Creole', longName: 'Louisiana Creole', id: 59, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Maharashtrian', longName: 'Maharashtrian', id: 60, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Mangalorean', longName: 'Mangalorean', id: 61, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Malay', longName: 'Malay', id: 62, source: sourceEnum.Yelp, sourceId: null },
    {
        tagName: 'Malaysian Chinese cuisine',
        longName: 'Malaysian Chinese cuisine',
        id: 63,
        source: sourceEnum.Yelp,
        sourceId: null,
    },
    {
        tagName: 'Malaysian Indian cuisine',
        longName: 'Malaysian Indian cuisine',
        id: 64,
        source: sourceEnum.Yelp,
        sourceId: null,
    },
    {
        tagName: 'Mediterranean cuisine',
        longName: 'Mediterranean cuisine',
        id: 65,
        source: sourceEnum.Yelp,
        sourceId: null,
    },
    { tagName: 'Mexican', longName: 'Mexican', id: 66, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Mordovian', longName: 'Mordovian', id: 67, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Mughal', longName: 'Mughal', id: 68, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Native American', longName: 'Native American', id: 69, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Nepalese', longName: 'Nepalese', id: 70, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'New Mexican', longName: 'New Mexican', id: 71, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Odia', longName: 'Odia', id: 72, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Parsi', longName: 'Parsi', id: 73, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Pashtun', longName: 'Pashtun', id: 74, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Polish', longName: 'Polish', id: 75, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Pennsylvania Dutch', longName: 'Pennsylvania Dutch', id: 76, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Pakistani', longName: 'Pakistani', id: 77, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Peranakan', longName: 'Peranakan', id: 78, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Persian', longName: 'Persian', id: 79, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Peruvian', longName: 'Peruvian', id: 80, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Portuguese', longName: 'Portuguese', id: 81, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Punjabi', longName: 'Punjabi', id: 82, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Rajasthani', longName: 'Rajasthani', id: 83, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Romanian', longName: 'Romanian', id: 84, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Russian', longName: 'Russian', id: 85, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Sami', longName: 'Sami', id: 86, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Serbian', longName: 'Serbian', id: 87, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Sindhi', longName: 'Sindhi', id: 88, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Slovak', longName: 'Slovak', id: 89, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Slovenian', longName: 'Slovenian', id: 90, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Somali', longName: 'Somali', id: 91, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'South Indian', longName: 'South Indian', id: 92, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Soviet', longName: 'Soviet', id: 93, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Spanish', longName: 'Spanish', id: 94, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Sri Lankan', longName: 'Sri Lankan', id: 95, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Taiwanese', longName: 'Taiwanese', id: 96, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Tatar', longName: 'Tatar', id: 97, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Thai', longName: 'Thai', id: 98, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Turkish', longName: 'Turkish', id: 99, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Tamil', longName: 'Tamil', id: 100, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Udupi', longName: 'Udupi', id: 101, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Ukrainian', longName: 'Ukrainian', id: 102, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Vietnamese', longName: 'Vietnamese', id: 103, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Yamal', longName: 'Yamal', id: 104, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Zambian', longName: 'Zambian', id: 105, source: sourceEnum.Yelp, sourceId: null },
    { tagName: 'Zanzibari', longName: 'Zanzibari', id: 106, source: sourceEnum.Yelp, sourceId: null },
]
