export enum ILocalPlacesTab {
    MOST_RECOMMENDED = 'MOST_RECOMMENDED',
    LATEST_RECOMMENDATIONS = 'LATEST_RECOMMENDATIONS',
    NEW_PLACES = 'NEW_PLACES',
    TRENDING_PLACES = 'TRENDING_PLACES',
}
